# Generated by Django 6.1 on 2026-08-09 16:58

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_seed_item_types_and_attributes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='character',
            name='unique_character_per_user_server',
        ),
        migrations.AddField(
            model_name='profile',
            name='auto_generate_item_names',
            field=models.BooleanField(default=False, help_text="Remembers this user's last choice for the 'auto-generate name from type and attributes' checkbox on the Add Item form."),
        ),
        migrations.AddField(
            model_name='profile',
            name='has_seen_character_intro',
            field=models.BooleanField(default=False, help_text="Set once the one-time 'you can create a character, or skip for now' screen has been shown after login/registration."),
        ),
        migrations.AlterField(
            model_name='item',
            name='name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddConstraint(
            model_name='character',
            constraint=models.UniqueConstraint(fields=('name', 'server'), name='unique_character_name_per_server'),
        ),
    ]
